/**
 * Player API
 * The Player API is a service to integrate your game with Beam
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "PlayerClientBaseModel.h"
#include "PlayerClientPlayerOperationAction.h"
#include "PlayerClientPlayerOperationResponseTransactionsInner.h"

namespace OpenAPI
{

/*
 * PlayerClientPlayerOperationResponse
 *
 * 
 */
class PLAYERCLIENT_API PlayerClientPlayerOperationResponse : public Model
{
public:
    virtual ~PlayerClientPlayerOperationResponse() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	enum class StatusEnum
	{
		Pending,
		_Signed,
		Rejected,
		Executed,
		Error,
  	};

	static FString EnumToString(const StatusEnum& EnumValue);
	static bool EnumFromString(const FString& EnumAsString, StatusEnum& EnumValue);
	StatusEnum Status;
	enum class ProcessingEnum
	{
		SignOnly,
		Execute,
  	};

	static FString EnumToString(const ProcessingEnum& EnumValue);
	static bool EnumFromString(const FString& EnumAsString, ProcessingEnum& EnumValue);
	ProcessingEnum Processing;
	enum class AuthProviderEnum
	{
		Any,
		Google,
		Discord,
		Apple,
  	};

	static FString EnumToString(const AuthProviderEnum& EnumValue);
	static bool EnumFromString(const FString& EnumAsString, AuthProviderEnum& EnumValue);
	AuthProviderEnum AuthProvider;
	FString Id;
	FDateTime CreatedAt;
	TOptional<FDateTime> UpdatedAt;
	FString GameId;
	FString UserId;
	int64 ChainId = 0;
	TArray<PlayerClientPlayerOperationAction> Actions;
	TArray<PlayerClientPlayerOperationResponseTransactionsInner> Transactions;
	FString Url;
};

}
