/**
 * Player API
 * The Player API is a service to integrate your game with Beam
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "PlayerClientPlayerOperationResponseTransactionsInner.h"

#include "PlayerClientModule.h"
#include "PlayerClientHelpers.h"

#include "Templates/SharedPointer.h"

namespace OpenAPI
{

inline FString ToString(const PlayerClientPlayerOperationResponseTransactionsInner::StatusEnum& Value)
{
	switch (Value)
	{
	case PlayerClientPlayerOperationResponseTransactionsInner::StatusEnum::Pending:
		return TEXT("Pending");
	case PlayerClientPlayerOperationResponseTransactionsInner::StatusEnum::_Signed:
		return TEXT("Signed");
	case PlayerClientPlayerOperationResponseTransactionsInner::StatusEnum::Rejected:
		return TEXT("Rejected");
	case PlayerClientPlayerOperationResponseTransactionsInner::StatusEnum::Executed:
		return TEXT("Executed");
	case PlayerClientPlayerOperationResponseTransactionsInner::StatusEnum::Error:
		return TEXT("Error");
	}

	UE_LOG(LogPlayerClient, Error, TEXT("Invalid PlayerClientPlayerOperationResponseTransactionsInner::StatusEnum Value (%d)"), (int)Value);
	return TEXT("");
}

FString PlayerClientPlayerOperationResponseTransactionsInner::EnumToString(const PlayerClientPlayerOperationResponseTransactionsInner::StatusEnum& EnumValue)
{
	return ToString(EnumValue);
}

inline bool FromString(const FString& EnumAsString, PlayerClientPlayerOperationResponseTransactionsInner::StatusEnum& Value)
{
	static TMap<FString, PlayerClientPlayerOperationResponseTransactionsInner::StatusEnum> StringToEnum = { 
		{ TEXT("Pending"), PlayerClientPlayerOperationResponseTransactionsInner::StatusEnum::Pending },
		{ TEXT("Signed"), PlayerClientPlayerOperationResponseTransactionsInner::StatusEnum::_Signed },
		{ TEXT("Rejected"), PlayerClientPlayerOperationResponseTransactionsInner::StatusEnum::Rejected },
		{ TEXT("Executed"), PlayerClientPlayerOperationResponseTransactionsInner::StatusEnum::Executed },
		{ TEXT("Error"), PlayerClientPlayerOperationResponseTransactionsInner::StatusEnum::Error }, };

	const auto Found = StringToEnum.Find(EnumAsString);
	if(Found)
		Value = *Found;

	return Found != nullptr;
}

bool PlayerClientPlayerOperationResponseTransactionsInner::EnumFromString(const FString& EnumAsString, PlayerClientPlayerOperationResponseTransactionsInner::StatusEnum& EnumValue)
{
	return FromString(EnumAsString, EnumValue);
}

inline void WriteJsonValue(JsonWriter& Writer, const PlayerClientPlayerOperationResponseTransactionsInner::StatusEnum& Value)
{
	WriteJsonValue(Writer, ToString(Value));
}

inline bool TryGetJsonValue(const TSharedPtr<FJsonValue>& JsonValue, PlayerClientPlayerOperationResponseTransactionsInner::StatusEnum& Value)
{
	FString TmpValue;
	if (JsonValue->TryGetString(TmpValue))
	{
		if(FromString(TmpValue, Value))
			return true;
	}
	return false;
}

inline FString ToString(const PlayerClientPlayerOperationResponseTransactionsInner::TypeEnum& Value)
{
	switch (Value)
	{
	case PlayerClientPlayerOperationResponseTransactionsInner::TypeEnum::OpenfortTransaction:
		return TEXT("OpenfortTransaction");
	case PlayerClientPlayerOperationResponseTransactionsInner::TypeEnum::OpenfortReservoirOrder:
		return TEXT("OpenfortReservoirOrder");
	case PlayerClientPlayerOperationResponseTransactionsInner::TypeEnum::OpenfortRevokeSession:
		return TEXT("OpenfortRevokeSession");
	}

	UE_LOG(LogPlayerClient, Error, TEXT("Invalid PlayerClientPlayerOperationResponseTransactionsInner::TypeEnum Value (%d)"), (int)Value);
	return TEXT("");
}

FString PlayerClientPlayerOperationResponseTransactionsInner::EnumToString(const PlayerClientPlayerOperationResponseTransactionsInner::TypeEnum& EnumValue)
{
	return ToString(EnumValue);
}

inline bool FromString(const FString& EnumAsString, PlayerClientPlayerOperationResponseTransactionsInner::TypeEnum& Value)
{
	static TMap<FString, PlayerClientPlayerOperationResponseTransactionsInner::TypeEnum> StringToEnum = { 
		{ TEXT("OpenfortTransaction"), PlayerClientPlayerOperationResponseTransactionsInner::TypeEnum::OpenfortTransaction },
		{ TEXT("OpenfortReservoirOrder"), PlayerClientPlayerOperationResponseTransactionsInner::TypeEnum::OpenfortReservoirOrder },
		{ TEXT("OpenfortRevokeSession"), PlayerClientPlayerOperationResponseTransactionsInner::TypeEnum::OpenfortRevokeSession }, };

	const auto Found = StringToEnum.Find(EnumAsString);
	if(Found)
		Value = *Found;

	return Found != nullptr;
}

bool PlayerClientPlayerOperationResponseTransactionsInner::EnumFromString(const FString& EnumAsString, PlayerClientPlayerOperationResponseTransactionsInner::TypeEnum& EnumValue)
{
	return FromString(EnumAsString, EnumValue);
}

inline void WriteJsonValue(JsonWriter& Writer, const PlayerClientPlayerOperationResponseTransactionsInner::TypeEnum& Value)
{
	WriteJsonValue(Writer, ToString(Value));
}

inline bool TryGetJsonValue(const TSharedPtr<FJsonValue>& JsonValue, PlayerClientPlayerOperationResponseTransactionsInner::TypeEnum& Value)
{
	FString TmpValue;
	if (JsonValue->TryGetString(TmpValue))
	{
		if(FromString(TmpValue, Value))
			return true;
	}
	return false;
}

void PlayerClientPlayerOperationResponseTransactionsInner::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("status")); WriteJsonValue(Writer, Status);
	Writer->WriteIdentifierPrefix(TEXT("id")); WriteJsonValue(Writer, Id);
	if (OpenfortId.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("openfortId")); WriteJsonValue(Writer, OpenfortId.GetValue());
	}
	Writer->WriteIdentifierPrefix(TEXT("sponsored")); WriteJsonValue(Writer, Sponsored);
	if (ActionId.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("actionId")); WriteJsonValue(Writer, ActionId.GetValue());
	}
	if (Hash.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("hash")); WriteJsonValue(Writer, Hash.GetValue());
	}
	if (Type.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("type")); WriteJsonValue(Writer, Type.GetValue());
	}
	if (ExternalId.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("externalId")); WriteJsonValue(Writer, ExternalId.GetValue());
	}
	if (Signature.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("signature")); WriteJsonValue(Writer, Signature.GetValue());
	}
	if (TransactionHash.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("transactionHash")); WriteJsonValue(Writer, TransactionHash.GetValue());
	}
	if (OperationId.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("operationId")); WriteJsonValue(Writer, OperationId.GetValue());
	}
	if (Data.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("data")); WriteJsonValue(Writer, Data.GetValue());
	}
	Writer->WriteObjectEnd();
}

bool PlayerClientPlayerOperationResponseTransactionsInner::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("status"), Status);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("id"), Id);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("openfortId"), OpenfortId);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("sponsored"), Sponsored);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("actionId"), ActionId);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("hash"), Hash);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("type"), Type);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("externalId"), ExternalId);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("signature"), Signature);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("transactionHash"), TransactionHash);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("operationId"), OperationId);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("data"), Data);

	return ParseSuccess;
}

}
