/**
 * Player API
 * The Player API is a service to integrate your game with Beam
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "PlayerClientPlayerOperationResponse.h"

#include "PlayerClientModule.h"
#include "PlayerClientHelpers.h"

#include "Templates/SharedPointer.h"

namespace OpenAPI
{

inline FString ToString(const PlayerClientPlayerOperationResponse::StatusEnum& Value)
{
	switch (Value)
	{
	case PlayerClientPlayerOperationResponse::StatusEnum::Pending:
		return TEXT("Pending");
	case PlayerClientPlayerOperationResponse::StatusEnum::_Signed:
		return TEXT("Signed");
	case PlayerClientPlayerOperationResponse::StatusEnum::Rejected:
		return TEXT("Rejected");
	case PlayerClientPlayerOperationResponse::StatusEnum::Executed:
		return TEXT("Executed");
	case PlayerClientPlayerOperationResponse::StatusEnum::Error:
		return TEXT("Error");
	}

	UE_LOG(LogPlayerClient, Error, TEXT("Invalid PlayerClientPlayerOperationResponse::StatusEnum Value (%d)"), (int)Value);
	return TEXT("");
}

FString PlayerClientPlayerOperationResponse::EnumToString(const PlayerClientPlayerOperationResponse::StatusEnum& EnumValue)
{
	return ToString(EnumValue);
}

inline bool FromString(const FString& EnumAsString, PlayerClientPlayerOperationResponse::StatusEnum& Value)
{
	static TMap<FString, PlayerClientPlayerOperationResponse::StatusEnum> StringToEnum = { 
		{ TEXT("Pending"), PlayerClientPlayerOperationResponse::StatusEnum::Pending },
		{ TEXT("Signed"), PlayerClientPlayerOperationResponse::StatusEnum::_Signed },
		{ TEXT("Rejected"), PlayerClientPlayerOperationResponse::StatusEnum::Rejected },
		{ TEXT("Executed"), PlayerClientPlayerOperationResponse::StatusEnum::Executed },
		{ TEXT("Error"), PlayerClientPlayerOperationResponse::StatusEnum::Error }, };

	const auto Found = StringToEnum.Find(EnumAsString);
	if(Found)
		Value = *Found;

	return Found != nullptr;
}

bool PlayerClientPlayerOperationResponse::EnumFromString(const FString& EnumAsString, PlayerClientPlayerOperationResponse::StatusEnum& EnumValue)
{
	return FromString(EnumAsString, EnumValue);
}

inline void WriteJsonValue(JsonWriter& Writer, const PlayerClientPlayerOperationResponse::StatusEnum& Value)
{
	WriteJsonValue(Writer, ToString(Value));
}

inline bool TryGetJsonValue(const TSharedPtr<FJsonValue>& JsonValue, PlayerClientPlayerOperationResponse::StatusEnum& Value)
{
	FString TmpValue;
	if (JsonValue->TryGetString(TmpValue))
	{
		if(FromString(TmpValue, Value))
			return true;
	}
	return false;
}

inline FString ToString(const PlayerClientPlayerOperationResponse::ProcessingEnum& Value)
{
	switch (Value)
	{
	case PlayerClientPlayerOperationResponse::ProcessingEnum::SignOnly:
		return TEXT("SignOnly");
	case PlayerClientPlayerOperationResponse::ProcessingEnum::Execute:
		return TEXT("Execute");
	}

	UE_LOG(LogPlayerClient, Error, TEXT("Invalid PlayerClientPlayerOperationResponse::ProcessingEnum Value (%d)"), (int)Value);
	return TEXT("");
}

FString PlayerClientPlayerOperationResponse::EnumToString(const PlayerClientPlayerOperationResponse::ProcessingEnum& EnumValue)
{
	return ToString(EnumValue);
}

inline bool FromString(const FString& EnumAsString, PlayerClientPlayerOperationResponse::ProcessingEnum& Value)
{
	static TMap<FString, PlayerClientPlayerOperationResponse::ProcessingEnum> StringToEnum = { 
		{ TEXT("SignOnly"), PlayerClientPlayerOperationResponse::ProcessingEnum::SignOnly },
		{ TEXT("Execute"), PlayerClientPlayerOperationResponse::ProcessingEnum::Execute }, };

	const auto Found = StringToEnum.Find(EnumAsString);
	if(Found)
		Value = *Found;

	return Found != nullptr;
}

bool PlayerClientPlayerOperationResponse::EnumFromString(const FString& EnumAsString, PlayerClientPlayerOperationResponse::ProcessingEnum& EnumValue)
{
	return FromString(EnumAsString, EnumValue);
}

inline void WriteJsonValue(JsonWriter& Writer, const PlayerClientPlayerOperationResponse::ProcessingEnum& Value)
{
	WriteJsonValue(Writer, ToString(Value));
}

inline bool TryGetJsonValue(const TSharedPtr<FJsonValue>& JsonValue, PlayerClientPlayerOperationResponse::ProcessingEnum& Value)
{
	FString TmpValue;
	if (JsonValue->TryGetString(TmpValue))
	{
		if(FromString(TmpValue, Value))
			return true;
	}
	return false;
}

inline FString ToString(const PlayerClientPlayerOperationResponse::AuthProviderEnum& Value)
{
	switch (Value)
	{
	case PlayerClientPlayerOperationResponse::AuthProviderEnum::Any:
		return TEXT("Any");
	case PlayerClientPlayerOperationResponse::AuthProviderEnum::Google:
		return TEXT("Google");
	case PlayerClientPlayerOperationResponse::AuthProviderEnum::Discord:
		return TEXT("Discord");
	case PlayerClientPlayerOperationResponse::AuthProviderEnum::Apple:
		return TEXT("Apple");
	}

	UE_LOG(LogPlayerClient, Error, TEXT("Invalid PlayerClientPlayerOperationResponse::AuthProviderEnum Value (%d)"), (int)Value);
	return TEXT("");
}

FString PlayerClientPlayerOperationResponse::EnumToString(const PlayerClientPlayerOperationResponse::AuthProviderEnum& EnumValue)
{
	return ToString(EnumValue);
}

inline bool FromString(const FString& EnumAsString, PlayerClientPlayerOperationResponse::AuthProviderEnum& Value)
{
	static TMap<FString, PlayerClientPlayerOperationResponse::AuthProviderEnum> StringToEnum = { 
		{ TEXT("Any"), PlayerClientPlayerOperationResponse::AuthProviderEnum::Any },
		{ TEXT("Google"), PlayerClientPlayerOperationResponse::AuthProviderEnum::Google },
		{ TEXT("Discord"), PlayerClientPlayerOperationResponse::AuthProviderEnum::Discord },
		{ TEXT("Apple"), PlayerClientPlayerOperationResponse::AuthProviderEnum::Apple }, };

	const auto Found = StringToEnum.Find(EnumAsString);
	if(Found)
		Value = *Found;

	return Found != nullptr;
}

bool PlayerClientPlayerOperationResponse::EnumFromString(const FString& EnumAsString, PlayerClientPlayerOperationResponse::AuthProviderEnum& EnumValue)
{
	return FromString(EnumAsString, EnumValue);
}

inline void WriteJsonValue(JsonWriter& Writer, const PlayerClientPlayerOperationResponse::AuthProviderEnum& Value)
{
	WriteJsonValue(Writer, ToString(Value));
}

inline bool TryGetJsonValue(const TSharedPtr<FJsonValue>& JsonValue, PlayerClientPlayerOperationResponse::AuthProviderEnum& Value)
{
	FString TmpValue;
	if (JsonValue->TryGetString(TmpValue))
	{
		if(FromString(TmpValue, Value))
			return true;
	}
	return false;
}

void PlayerClientPlayerOperationResponse::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("status")); WriteJsonValue(Writer, Status);
	Writer->WriteIdentifierPrefix(TEXT("processing")); WriteJsonValue(Writer, Processing);
	Writer->WriteIdentifierPrefix(TEXT("authProvider")); WriteJsonValue(Writer, AuthProvider);
	Writer->WriteIdentifierPrefix(TEXT("id")); WriteJsonValue(Writer, Id);
	Writer->WriteIdentifierPrefix(TEXT("createdAt")); WriteJsonValue(Writer, CreatedAt);
	if (UpdatedAt.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("updatedAt")); WriteJsonValue(Writer, UpdatedAt.GetValue());
	}
	Writer->WriteIdentifierPrefix(TEXT("gameId")); WriteJsonValue(Writer, GameId);
	Writer->WriteIdentifierPrefix(TEXT("userId")); WriteJsonValue(Writer, UserId);
	Writer->WriteIdentifierPrefix(TEXT("chainId")); WriteJsonValue(Writer, ChainId);
	Writer->WriteIdentifierPrefix(TEXT("actions")); WriteJsonValue(Writer, Actions);
	Writer->WriteIdentifierPrefix(TEXT("transactions")); WriteJsonValue(Writer, Transactions);
	Writer->WriteIdentifierPrefix(TEXT("url")); WriteJsonValue(Writer, Url);
	Writer->WriteObjectEnd();
}

bool PlayerClientPlayerOperationResponse::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("status"), Status);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("processing"), Processing);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("authProvider"), AuthProvider);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("id"), Id);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("createdAt"), CreatedAt);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("updatedAt"), UpdatedAt);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("gameId"), GameId);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("userId"), UserId);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("chainId"), ChainId);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("actions"), Actions);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("transactions"), Transactions);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("url"), Url);

	return ParseSuccess;
}

}
