/**
 * Player API
 * The Player API is a service to integrate your game with Beam
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "PlayerClientConfirmOperationRequest.h"

#include "PlayerClientModule.h"
#include "PlayerClientHelpers.h"

#include "Templates/SharedPointer.h"

namespace OpenAPI
{

inline FString ToString(const PlayerClientConfirmOperationRequest::StatusEnum& Value)
{
	switch (Value)
	{
	case PlayerClientConfirmOperationRequest::StatusEnum::Pending:
		return TEXT("Pending");
	case PlayerClientConfirmOperationRequest::StatusEnum::_Signed:
		return TEXT("Signed");
	case PlayerClientConfirmOperationRequest::StatusEnum::Rejected:
		return TEXT("Rejected");
	case PlayerClientConfirmOperationRequest::StatusEnum::Executed:
		return TEXT("Executed");
	case PlayerClientConfirmOperationRequest::StatusEnum::Error:
		return TEXT("Error");
	}

	UE_LOG(LogPlayerClient, Error, TEXT("Invalid PlayerClientConfirmOperationRequest::StatusEnum Value (%d)"), (int)Value);
	return TEXT("");
}

FString PlayerClientConfirmOperationRequest::EnumToString(const PlayerClientConfirmOperationRequest::StatusEnum& EnumValue)
{
	return ToString(EnumValue);
}

inline bool FromString(const FString& EnumAsString, PlayerClientConfirmOperationRequest::StatusEnum& Value)
{
	static TMap<FString, PlayerClientConfirmOperationRequest::StatusEnum> StringToEnum = { 
		{ TEXT("Pending"), PlayerClientConfirmOperationRequest::StatusEnum::Pending },
		{ TEXT("Signed"), PlayerClientConfirmOperationRequest::StatusEnum::_Signed },
		{ TEXT("Rejected"), PlayerClientConfirmOperationRequest::StatusEnum::Rejected },
		{ TEXT("Executed"), PlayerClientConfirmOperationRequest::StatusEnum::Executed },
		{ TEXT("Error"), PlayerClientConfirmOperationRequest::StatusEnum::Error }, };

	const auto Found = StringToEnum.Find(EnumAsString);
	if(Found)
		Value = *Found;

	return Found != nullptr;
}

bool PlayerClientConfirmOperationRequest::EnumFromString(const FString& EnumAsString, PlayerClientConfirmOperationRequest::StatusEnum& EnumValue)
{
	return FromString(EnumAsString, EnumValue);
}

inline void WriteJsonValue(JsonWriter& Writer, const PlayerClientConfirmOperationRequest::StatusEnum& Value)
{
	WriteJsonValue(Writer, ToString(Value));
}

inline bool TryGetJsonValue(const TSharedPtr<FJsonValue>& JsonValue, PlayerClientConfirmOperationRequest::StatusEnum& Value)
{
	FString TmpValue;
	if (JsonValue->TryGetString(TmpValue))
	{
		if(FromString(TmpValue, Value))
			return true;
	}
	return false;
}

void PlayerClientConfirmOperationRequest::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("status")); WriteJsonValue(Writer, Status);
	if (Transactions.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("transactions")); WriteJsonValue(Writer, Transactions.GetValue());
	}
	if (Actions.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("actions")); WriteJsonValue(Writer, Actions.GetValue());
	}
	Writer->WriteObjectEnd();
}

bool PlayerClientConfirmOperationRequest::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("status"), Status);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("transactions"), Transactions);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("actions"), Actions);

	return ParseSuccess;
}

}
